### ISSUE TITLE
Saw the TG message, posible solution.

### ISSUE THREAD

**Issue by wcatz** [DevStakePool/thoth-bot#25]
Reach out to PSB or BBHMM. I doubt they would mind you using their instances they maintain for Tosidrop. They respond way faster and are load balanced between the two.

Thank you for the product.

**Comment by slux83** [comment]
Thank you! I'll contact Boris

**Comment by reqlez** [comment]
@wcatz "Saw the TG message, posible solution." is a horrible issue title lol

I got message from Alessio about some limits, but i don't understand what limits.

We will have a Public tier and also a Free tier moving forward.

Public tier does not require API key registration, however, the Free tier does, and has increased API calls per day quota.

What errors are you getting  or can you tell me more about the issue? because as far as i'm aware, we have not implemented the changes to the tiers yet.

**Comment by wcatz** [comment]
I feel it's one of my best issue titles.
